name = "PowerSeriesIVP"
uuid = "1f6b2684-f5ab-48e0-9d4d-8106aa97952d"
authors = ["Roy Wang"]
version = "0.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"


[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test","Random"]
